Feature/add communes
NachoRaik/tdp2-tp0-backend pull request #2
Opened 2021-04-18 01:50 UTC by matiscakosky

2021-04-18 15:06 UTC, NachoRaik commented on src/routes/communesRouter.js
> +const POINT_REGEX = /POINT ()(?::(.+))?>/;
We should consider deleting this, from both files (also operative), as it is not being used.

2021-04-19 00:20 UTC, matiscakosky commented on src/routes/communesRouter.js
> +const POINT_REGEX = /POINT ()(?::(.+))?>/;
habla en español, gil

2021-04-19 01:40 UTC, NachoRaik requested changes

2021-04-19 01:40 UTC, NachoRaik commented on src/routes/operativesRouter.js
> +  fs.createReadStream('resources/operativo-detectar.csv')
No deberia hacer falta leer el archivo 2 veces. Sobre lo que se cargo en results, en el endpoint directamente filtraria eso.

2021-04-19 01:40 UTC, NachoRaik commented on src/routes/operativesRouter.js
> +const communes = []
```suggestion
const communes = [];
```

2021-04-19 01:40 UTC, NachoRaik commented on src/routes/operativesRouter.js
>  const POINT_REGEX = /POINT ()(?::(.+))?>/;
Aprovecharia para borrar esto que quedo al pedo.

2021-04-19 01:40 UTC, NachoRaik commented on src/routes/operativesRouter.js
> +  fs.createReadStream('resources/operativo-detectar.csv')
O en el mismo `on('data')` de la lectura de arriba, leeria la comuna para guardarla en un diccionario/set:

```
    # Si es un Set --> communes.add(data['comuna'])
    # Si es un object --> communes[data['comuna']] = data['comuna']

    let [x, y] = pointToXAndY(data.WKT);
    data['x'] = x;
    data['y'] = y;
    delete data['WKT'];
    return results.push(data);
```

2021-04-19 01:40 UTC, NachoRaik commented on src/routes/operativesRouter.js
> +const communes = []
En vez de hacerlo una lista, lo haria un object (`{}`) o un set (creo que es `Set()`)

2021-04-19 01:40 UTC, NachoRaik commented on src/routes/operativesRouter.js
> +  fs.createReadStream('resources/operativo-detectar.csv')
Hecho asi, en el endpoint solo haria falta darle el formato que se le quiera dar (lista de strings, o lista de objetos `{'comuna': <comuna>}` como estabas haciendo).

2021-04-19 03:30 UTC, NachoRaik approved these changes

2021-04-19 17:12 UTC, merged